--- 부서 테이블 생성 
CREATE TABLE DEPT_T(
    DEPT_NO         NUMBER                NOT NULL PRIMARY KEY,
    DEPT_NAME       VARCHAR2(50 byte),
    DEPT_LOCATION   VARCHAR2(50 byte)
);

--- 사원 테이블 생성 (부서명은 부서번호로부터 가져옴)
CREATE TABLE EMPLOYEE_T(
    EMPLOYEE_NO     NUMBER  NOT NULL PRIMARY KEY,
    EMPLOYEE_NAME   VARCHAR2(100 byte),
    DEPT_NO         NUMBER REFERENCES DEPT_T(DEPT_NO) ON DELETE SET NULL,
    EMPLOYEE_PO     VARCHAR2(100 byte),
    HIRE_DATE       DATE,
    SALARY          NUMBER
);
--- 프로젝트 테이블 생성
CREATE TABLE PJT_T(
    PJT_NO      NUMBER NOT NULL PRIMARY KEY,
    PJT_NAME    VARCHAR2(100 byte),
    BEGIN_DATE  DATE,
    END_DATE    DATE
);

--- 프로젝트에 참여한 사원 테이블 생성
CREATE TABLE PROCEEDING_T(
    EMPLOYEE_NO NUMBER  REFERENCES EMPLOYEE_T(EMPLOYEE_NO) ON DELETE CASCADE,
    PJT_NO      NUMBER  REFERENCES PJT_T(PJT_NO) ON DELETE SET NULL,
    PJT_STATE   NUMBER  NOT NULL
);

--- 프로젝트 진행 테이블 삭제
DROP TABLE PROCEEDING_T; 
--- 프로젝트 테이블 삭제
DROP TABLE PJT_T;
--- 사원 테이블 삭제
DROP TABLE EMPLOYEE_T;
--- 부서 테이블 삭제
DROP TABLE DEPT_T;